### ISSUE TITLE
seafile-ce-uberspace

### ISSUE THREAD

**Issue by lebochequirit** [SeafileDE/seafile-server-installer#55]
Hi.
Auch mit den Änderungen von https://github.com/SeafileDE/seafile-server-installer/commit/3742362b6975b159f9bf30295f5a1d0e03d1367b
wird das Skript Fehler aus.
- das Uninstall-Skript löscht in Zeile 56 mit ~/bin/seafile den ganzen ~/bin-Ordner, so dass eine erneute Installation Fehler produziert, weil ~/bin/seafile nicht geschrieben werden kann.

Mein Uberspace ist wegen zahlreicher Installationsversuche nicht "fresh", es läuft aber auch nicht anderes darauf. Ich habe  mit dem Uninstallskript und händisch alle mir erkennbaren Spuren entfernt.
Mehr kann und werde ich nicht bieten  - Uberspace hat einen hervorragenden Support, der Euch garantiert beim Troubleshooten hilft und sich freut, wenn nicht -zig User für jeden neuen Versuch einen neuen Uberspace anlegen.

Nach dem Aufräumen läuft die Installation durch, Seafile wirft aber einen Server hiccup aus, sobald man versucht, sich einzuloggen. Der erste Seitenaufruf funktioniert.

~/seafile/seafile.log:

> ```
> [01/03/16 00:00:33] seafile-session.c(79): Failed to load config file.
> [01/03/16 00:00:33] seaf-server.c(939): Failed to create seafile session.
> ```

~/seafile/ccnet.log:

> [01/03/16 00:10:42] ../common/session.c(398): Accepted a local client
> [01/03/16 00:10:42] ../common/session.c(398): Accepted a local client
> [01/03/16 00:10:42] ../common/peer.c(941): libevent got an error! what=33, errno=104 (Connection reset by peer)

~/seafile/seahub.log:

> ```
> 2016-01-03 00:02:09,912 [ERROR] seahub.views.sysadmin:480 _populate_user_quota_usage Error received: 511 Unknown service (In _start_service)
> ```

~/seafile/seahub_django-request.log:

```
>     2016-01-03 00:01:01,102 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>      response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/base/decorators.py", line 39, in _decorated
>         return func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1266, in libraries
>         create_default_library(request)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1200, in create_default_library
>         passwd=None)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 50, in create_repo
>         return seafserv_threaded_rpc.create_repo(name, desc, username, passwd)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
>     2016-01-03 00:01:38,309 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/base/decorators.py", line 39, in _decorated
>         return func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1266, in libraries
>         create_default_library(request)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1200, in create_default_library
>         passwd=None)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 50, in create_repo
>         return seafserv_threaded_rpc.create_repo(name, desc, username, passwd)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
>     2016-01-03 00:01:46,271 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/base/decorators.py", line 39, in _decorated
>         return func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1266, in libraries
>         create_default_library(request)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/__init__.py", line 1200, in create_default_library
>         passwd=None)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 50, in create_repo
>         return seafserv_threaded_rpc.create_repo(name, desc, username, passwd)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
>     2016-01-03 00:02:03,296 [WARNING] django.request:144 get_response Not Found: /seahub
>     2016-01-03 00:02:06,759 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /ajax/space_and_traffic/
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 69, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/ajax.py", line 1608, in space_and_traffic
>         space_quota = seafile_api.get_user_quota(username)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 337, in get_user_quota
>         return seafserv_threaded_rpc.get_user_quota(username)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
>     2016-01-03 00:02:34,456 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /sys/seafadmin/
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/base/decorators.py", line 25, in _decorated
>         return func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/sysadmin.py", line 158, in sys_repo_admin
>         per_page + 1)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 62, in get_repo_list
>         return seafserv_threaded_rpc.get_repo_list(start, limit)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
>     2016-01-03 00:08:11,212 [WARNING] django.request:144 get_response Not Found: /seahub
>     2016-01-03 00:08:56,784 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /ajax/space_and_traffic/
>     Traceback (most recent call last):
>       File "/home/USER/seafile/seafile-server-latest/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
>         response = callback(request, *callback_args, **callback_kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/auth/decorators.py", line 69, in _wrapped_view
>         return view_func(request, *args, **kwargs)
>       File "/home/USER/seafile/seafile-server-latest/seahub/seahub/views/ajax.py", line 1608, in space_and_traffic
>         space_quota = seafile_api.get_user_quota(username)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 337, in get_user_quota
>         return seafserv_threaded_rpc.get_user_quota(username)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 110, in newfunc
>         ret_str = self.call_remote_func_sync(fcall_str)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 75, in call_remote_func_sync
>         req_id = self._start_service(client)
>       File "/home/USER/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/ccnet/rpc.py", line 36, in _start_service
>         raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
>     SearpcError: Error received: 511 Unknown service (In _start_service)
```

Ich hoffe, das hilft etwas.

L.B.Q.R.

**Comment by 0x64746b** [comment]
Ftr: Während auf meinem (nicht frischen, aber gut gepflegten ;)) Uberspace der Installer ohne Fehler durchläuft, schlägt das Einloggen mit den gleichen Symptomen fehl (nur dass bei mir das `~/seafile/logs/seahub.log` leer bleibt).

Ich vermute, der Fehler [tritt hier auf](https://github.com/haiwen/seafile/blob/master/server/seafile-session.c#L77). Da das zu dem in dem `ccnet.log` auftretenden `libevent`-Fehler passen könnte, könnte es sich um ein Problem beim Laden der `conf/ccnet.conf` handeln?

**Comment by alexanderjackson** [comment]
Das seafile-ce-uberspace Installer-Skript wird aus Zeitmangel nicht mehr von mir weitergepflegt. Ich schließe daher dieses Issue.
